### ISSUE TITLE
maven configuration

### ISSUE THREAD

**Issue by Walter-Kuhn** [mklemm/jaxb-delegate-plugin#2]
Hi, using IntelliJ and maven 3.5, I cannot include the plugin. Neither args is accepted (Arguments is) not the plugin in the plugin. Any idea?
As I got 7 XSDs (each individually), I might have a special structure:
...
                    ```
```
<execution>
                        <id>serviceTest</id>
                        <phase>generate-sources</phase>
                        <goals><goal>xjc</goal></goals>
                        <configuration>
                            <packageName>com.mywork.input.servicetest</packageName>
                         <sources><source>${project.basedir}/src/main/xsd/serviceTest.xsd</source></sources>
                            <arguments>
                                <argument>-Xdelegate</argument>
                            </arguments>
                        </configuration>

                    </execution>

``````

**Comment by mklemm** [comment]
You will have to add the plugin artifact to the maven-jaxb-plugin configuration. Please look at the README on how to do that...
